// Import necessary dependencies and CSS
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

// Initialize Inter font
const inter = Inter({ subsets: ["latin"] });

// Define metadata for the page
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex, nofollow" />

        <title>Shadab Kham – Personal Portfolio </title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
        {/* Stylesheets */}
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=5.9.6"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/tj-gerold-core/assets/css/tjcore.css?ver=1.1.2"
        />
        <link
          rel="stylesheet"
          href="//fonts.googleapis.com/css?family=Russo+One%3Aital%2Cwght%400%2C400%26display%3Dswap%7CSora%3Aital%2Cwght%400%2C300%3B0%2C400%3B0%2C500%3B0%2C700%3B1%2C300%3B1%2C400%3B1%2C500%3B1%2C700%26display%3Dswap%26display%3Dswap&amp;subset=latin%2Clatin-ext"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/bootstrap.min.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/font-awesome-pro.min.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/animate.min.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/meanmenu.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/nice-select.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/flaticon_gerold.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/owl.carousel.min.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/odometer-theme-default.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/magnific-popup.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/swiper.min.css?ver=6.5.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-core.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-core-2.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-light-mode.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-responsive.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-responsive-2.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-unit.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold/assets/css/gerold-custom.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/themes/gerold-child/style.css?ver=1.1.2"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/elementor/assets/lib/eicons/css/elementor-icons.min.css?ver=5.30.0"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/uploads/elementor/css/custom-frontend-lite.min.css?ver=1718271534"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/elementor/assets/lib/swiper/v8/css/swiper.min.css?ver=8.4.5"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/uploads/elementor/css/post-7.css?ver=1718271534"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/uploads/elementor/css/global.css?ver=1718271534"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/uploads/elementor/css/post-943.css?ver=1718271534"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/tj-gerold-core/inc/icons/flaticon/css/flaticon_gerold.css?ver=1.0.0"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/elementor/assets/lib/font-awesome/css/fontawesome.min.css?ver=5.15.3"
          media="all"
        />
        <link
          rel="stylesheet"
          href="https://geroldlight.themejunction.net/wp-content/plugins/elementor/assets/lib/font-awesome/css/brands.min.css?ver=5.15.3"
          media="all"
        />

        {/* JavaScript Scripts */}
        <script src="https://geroldlight.themejunction.net/wp-includes/js/jquery/jquery.min.js?ver=3.7.1"></script>
        <script src="https://geroldlight.themejunction.net/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1"></script>

        {/* WordPress Links */}
        <link rel="https://api.w.org/" href="https://geroldlight.themejunction.net/wp-json/" />
        <link
          rel="alternate"
          type="application/json"
          href="https://geroldlight.themejunction.net/wp-json/wp/v2/pages/943"
        />
        <link
          rel="EditURI"
          type="application/rsd+xml"
          title="RSD"
          href="https://geroldlight.themejunction.net/xmlrpc.php?rsd"
        />
        <link rel="canonical" href="https://geroldlight.themejunction.net/" />
        <link rel="shortlink" href="https://geroldlight.themejunction.net/" />
        <link
          rel="alternate"
          type="application/json+oembed"
          href="https://geroldlight.themejunction.net/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fgeroldlight.themejunction.net%2F"
        />
        <link
          rel="alternate"
          type="text/xml+oembed"
          href="https://geroldlight.themejunction.net/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fgeroldlight.themejunction.net%2F&#038;format=xml"
        />

        {/* Favicon and Icons */}
        <link
          rel="icon"
          href="https://geroldlight.themejunction.net/wp-content/uploads/2024/05/cropped-favicon-32x32.png"
          sizes="32x32"
        />
        <link
          rel="icon"
          href="https://geroldlight.themejunction.net/wp-content/uploads/2024/05/cropped-favicon-192x192.png"
          sizes="192x192"
        />
        <link
          rel="apple-touch-icon"
          href="https://geroldlight.themejunction.net/wp-content/uploads/2024/05/cropped-favicon-180x180.png"
        />
        <meta
          name="msapplication-TileImage"
          content="https://geroldlight.themejunction.net/wp-content/uploads/2024/05/cropped-favicon-270x270.png"
        />

        {/* Elementor */}
        <meta
          name="generator"
          content="Elementor 3.22.2; features: e_optimized_assets_loading, e_optimized_css_loading, additional_custom_breakpoints, e_lazyload; settings: css_print_method-external, google_font-enabled, font_display-swap"
        />
      </head>

      {/* Render the body with Inter font */}
      <body className={inter.className}>
        {children}

      </body>
    </html>
  );
}
